### ISSUE TITLE
BPE does not help to improve performance?

### ISSUE THREAD

**Issue by yuanenming** [nstrodt/UDSMProt#1]
Very detailed analysis!

It seems that you have tried BPE encoding. (I saw BPE part in your data-process scripts) I am just curious is it helpful?

**Comment by nstrodt** [comment]
Thanks!

I ran a few experiments with BPE encoding since I expected it to be useful- but did not see any significant improvements back then. I did not run any extensive tests, so it might be worth looking into it again. Let me know if you give it a try.
