### ISSUE TITLE
Using new dataset for classification

### ISSUE THREAD

**Issue by P260** [nstrodt/UDSMProt#3]
Hi, thank you for the amazing work!
I am just curious if I have my own dataset for which I would like to use your model architecture for protein classification, then what would be the best way to do that? 

Also, I am not able to find these Enzyme classification datasets in the repository which are mentioned in code.
path_ec_knna = git_data_path/"suppa.txt"
path_ec_knnb = git_data_path/"suppb.txt"

Thanks.

**Comment by P260** [comment]
Never mind. I understood the way out of it. Thanks.

**Comment by nstrodt** [comment]
sorry for the delayed response- it was on my todo-list but apparently I was not fast enough- feel free to ask again in case of any questions. I will do my best to respond quickly...

**Comment by P260** [comment]
@nstrodt Sure, thanks!

**Comment by BinhongLiu** [comment]
Hi @P260 
Could you share the two Enzyme classification datasets? I also found the missing of these two files but had no idea how to get them. Thanks!
